version: "3"

services:
    client:
        build:
            context: .
            dockerfile: Dockerfile.client
        ports:
            - "3000:3000"
        environment:
            - NODE_ENV=production

    server:
        build:
            context: .
            dockerfile: Dockerfile.server
        ports:
            - "4000:4000"
        environment:
            - NODE_ENV=development
            - DATABASE_URL=postgresql://postgres:alekseyVV9436@localhost:5432/chat_db?schema=public
        depends_on:
            - db

    db:
        image: postgres:14
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: mydatabase
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
